"""Create Stored Procedure

Revision ID: ab9f6b0bb3f2
Revises: 89cecc812f66
Create Date: 2023-09-01 12:17:09.799159

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ab9f6b0bb3f2'
down_revision: Union[str, None] = '89cecc812f66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Создается хранимая процедура, заполняющая таблицу 'value' текущей датой временем
    # в поле time и случайным значением от 0 до 10 в поле value
    op.execute("""
        CREATE OR REPLACE FUNCTION insert_random_value()
        RETURNS VOID AS $$
        BEGIN
            INSERT INTO value (time, value)
            VALUES (NOW(), CAST((RANDOM() * 10) AS NUMERIC(10, 2)));
        END;
        $$ LANGUAGE plpgsql;
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP FUNCTION IF EXISTS insert_random_value();")
    # ### end Alembic commands ###
