"""Create TriggerTime table

Revision ID: 2577b8c3fcf5
Revises: ab9f6b0bb3f2
Create Date: 2023-09-01 13:08:58.554622

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2577b8c3fcf5'
down_revision: Union[str, None] = 'ab9f6b0bb3f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trigger_time',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('time', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_trigger_time_id'), 'trigger_time', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trigger_time_id'), table_name='trigger_time')
    op.drop_table('trigger_time')
    # ### end Alembic commands ###
