"""Database init

Revision ID: 71c0fa6991c4
Revises: 
Create Date: 2023-08-30 00:22:29.100942

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '71c0fa6991c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('permission', sa.JSON(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_table('value',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('time', sa.DateTime(), nullable=True),
                    sa.Column('value', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_value_id'), 'value', ['id'], unique=False)
    op.create_table('user',
                    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(),
                              nullable=False),
                    sa.Column('email', sa.String(length=320), nullable=False),
                    sa.Column('username', sa.String(length=120), nullable=False),
                    sa.Column('registered_at', sa.DateTime(), nullable=False),
                    sa.Column('role_id', sa.Integer(), nullable=False),
                    sa.Column('hashed_password', sa.String(length=1024),
                              nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_superuser', sa.Boolean(), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_value_id'), table_name='value')
    op.drop_table('value')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_table('role')
    # ### end Alembic commands ###
